#!/system/bin/sh

##ZeroProjectX

sleep 5

echo '1' > /sys/block/mmcblk0/queue/rq_affinity
# echo '1' > /sys/block/mmcblk0/queue/add_random
# echo '1' > /sys/block/mmcblk0/queue/rotational
echo '1024' > /sys/block/mmcblk0/queue/read_ahead_kb
echo '1' > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
echo 'Y' > /sys/module/adreno_idler/parameters/adreno_idler_active
echo '8000' > /sys/module/adreno_idler/parameters/adreno_idler_idleworkloads
echo '10' > /sys/module/adreno_idler/parameters/adreno_idler_idlewait
# echo '1' > /sys/kernel/power_suspend/power_suspend_state
# echo '30' > /proc/sys/vm/swappiness
echo '1' > /sys/module/snd_soc_msm8x16_wcd/parameters/high_perf_mode
sleep 20

echo '21' > /sys/class/timed_output/vibrator/vtg_level
echo '1' > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus